### ISSUE TITLE
File saving doesn't work

### ISSUE THREAD

**Issue by MuTsunTsai** [NeVeSpl/MermaidEditorForVisualStudio#2]
When I press "Save *.png file next to *.mmd file" button, nothing happens. No file is being generated, and there's no error message either. Just nothing.

Visual Studio 17.5.4
Mermaid Editor 10.1.0.0

**Comment by MuTsunTsai** [comment]
Confirmed issue fixed in 10.1.0.1

**Comment by Love-Hitek** [comment]
Seems to be a problem again saving.  Using 11.3

**Comment by NeVeSpl** [comment]
> Seems to be a problem again saving. Using 11.3

I have just checked with Visual Studio 17.11.4, and everything works fine. 

If a problem still appears, please create a new issue and provide more details.
